-- Add service_booking_payments to create_tenant_schema for new tenants
CREATE OR REPLACE FUNCTION public.create_tenant_schema(
    p_tenant_id UUID,
    p_schema_name VARCHAR(63)
) RETURNS void AS $$
DECLARE
    v_schema VARCHAR(63);
BEGIN
    v_schema := LOWER(REGEXP_REPLACE(p_schema_name, '[^a-zA-Z0-9_]', '_', 'g'));
    IF LENGTH(v_schema) > 63 THEN
        v_schema := LEFT(v_schema, 63);
    END IF;
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.users (user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, name TEXT, phone VARCHAR(50), role VARCHAR(50) NOT NULL DEFAULT ''customer'' CHECK (role IN (''super_admin'', ''owner'', ''staff'', ''customer'', ''assistant_admin'', ''courier'')), two_factor_enabled BOOLEAN DEFAULT false, business_id UUID, business_name VARCHAR(255), pricing_plan VARCHAR(50), branding_enabled BOOLEAN DEFAULT false, branding_name VARCHAR(255), branding_logo_url TEXT, branding_primary_color VARCHAR(32), branding_secondary_color VARCHAR(32), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, UNIQUE(email))', v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.verification_codes (code_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE CASCADE, verification_code VARCHAR(10) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.password_reset_tokens (token_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE CASCADE, token VARCHAR(255) UNIQUE, token_hash VARCHAR(64), expires_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.product_categories (category_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL UNIQUE, display_order INTEGER NOT NULL DEFAULT 0)', v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.products (product_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, category VARCHAR(100), price DECIMAL(15, 2) NOT NULL, quantity INTEGER NOT NULL DEFAULT 0, description TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, business_id UUID)', v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.inventory_images (image_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES %I.products(product_id) ON DELETE CASCADE, image_url VARCHAR(500) NOT NULL, is_main BOOLEAN DEFAULT false, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.orders (order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE RESTRICT, order_number VARCHAR(50) NOT NULL UNIQUE, total_amount DECIMAL(15, 2) NOT NULL, order_status VARCHAR(50) NOT NULL DEFAULT ''pending'' CHECK (order_status IN (''pending'', ''confirmed'', ''processing'', ''shipped'', ''delivered'', ''cancelled'')), shipping_address TEXT, delivery_mode VARCHAR(50) NOT NULL DEFAULT ''SELLER_SELF'' CHECK (delivery_mode IN (''SELLER_SELF'', ''COURIER'', ''RIDER_MARKETPLACE'', ''CUSTOMER_PICKUP'')), shipping_fee DECIMAL(15, 2) NOT NULL DEFAULT 0, ordered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.order_items (order_item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES %I.orders(order_id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES %I.products(product_id) ON DELETE RESTRICT, inventory_image_id UUID REFERENCES %I.inventory_images(image_id) ON DELETE SET NULL, quantity INTEGER NOT NULL CHECK (quantity > 0), price_at_order DECIMAL(15, 2) NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema, v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.payments (payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES %I.orders(order_id) ON DELETE RESTRICT, user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE RESTRICT, amount DECIMAL(15, 2) NOT NULL, transaction_id TEXT, payment_status VARCHAR(50) NOT NULL DEFAULT ''pending'' CHECK (payment_status IN (''pending'', ''completed'', ''failed'', ''cancelled'')), payment_method VARCHAR(50) DEFAULT ''M-Pesa'', created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.shipments (shipment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID NOT NULL REFERENCES %I.orders(order_id) ON DELETE RESTRICT, assigned_courier_id UUID REFERENCES %I.users(user_id), delivery_mode VARCHAR(50) NOT NULL DEFAULT ''SELLER_SELF'' CHECK (delivery_mode IN (''SELLER_SELF'', ''COURIER'', ''RIDER_MARKETPLACE'', ''CUSTOMER_PICKUP'')), courier_service VARCHAR(100), tracking_number VARCHAR(100), rider_name VARCHAR(255), rider_phone VARCHAR(50), rider_vehicle VARCHAR(100), rider_job_id VARCHAR(100), pickup_location TEXT, status VARCHAR(50) NOT NULL DEFAULT ''CREATED'' CHECK (status IN (''CREATED'', ''PICKED_UP'', ''IN_TRANSIT'', ''OUT_FOR_DELIVERY'', ''READY_FOR_PICKUP'', ''DELIVERED'', ''COLLECTED'', ''ESCROW_RELEASED'')), shipped_at TIMESTAMP WITH TIME ZONE, delivered_at TIMESTAMP WITH TIME ZONE, otp_code VARCHAR(10), otp_verified_at TIMESTAMP WITH TIME ZONE, escrow_released_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.expenses (expense_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), category VARCHAR(64) NOT NULL, amount DECIMAL(15, 2) NOT NULL, description TEXT, receipt_reference VARCHAR(255), expense_date DATE NOT NULL, created_by_user_id UUID REFERENCES %I.users(user_id) ON DELETE SET NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.service_categories (category_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(100) NOT NULL UNIQUE, display_order INTEGER NOT NULL DEFAULT 0)', v_schema);
    EXECUTE format('INSERT INTO %I.service_categories (category_id, name, display_order) VALUES (gen_random_uuid(), ''Consulting'', 1), (gen_random_uuid(), ''Repair & Maintenance'', 2), (gen_random_uuid(), ''Training'', 3), (gen_random_uuid(), ''Health & Wellness'', 4), (gen_random_uuid(), ''Beauty & Personal Care'', 5), (gen_random_uuid(), ''Legal'', 6), (gen_random_uuid(), ''Accounting & Finance'', 7), (gen_random_uuid(), ''Cleaning'', 8), (gen_random_uuid(), ''Events'', 9), (gen_random_uuid(), ''IT & Tech Support'', 10), (gen_random_uuid(), ''Photography & Videography'', 11), (gen_random_uuid(), ''Catering & Food Service'', 12), (gen_random_uuid(), ''Security Services'', 13), (gen_random_uuid(), ''Logistics & Delivery'', 14), (gen_random_uuid(), ''Real Estate'', 15), (gen_random_uuid(), ''Insurance'', 16), (gen_random_uuid(), ''Marketing & Advertising'', 17), (gen_random_uuid(), ''Design (Graphic, Interior, Web)'', 18), (gen_random_uuid(), ''Writing & Editing'', 19), (gen_random_uuid(), ''Translation & Interpretation'', 20), (gen_random_uuid(), ''Tutoring & Education'', 21), (gen_random_uuid(), ''Coaching & Mentoring'', 22), (gen_random_uuid(), ''Fitness & Personal Training'', 23), (gen_random_uuid(), ''Pet Care'', 24), (gen_random_uuid(), ''Gardening & Landscaping'', 25), (gen_random_uuid(), ''Plumbing'', 26), (gen_random_uuid(), ''Electrical'', 27), (gen_random_uuid(), ''HVAC & Cooling'', 28), (gen_random_uuid(), ''Moving & Relocation'', 29), (gen_random_uuid(), ''Storage'', 30), (gen_random_uuid(), ''Printing & Copying'', 31), (gen_random_uuid(), ''Tailoring & Alterations'', 32), (gen_random_uuid(), ''Vehicle Repair & Auto Service'', 33), (gen_random_uuid(), ''Salon & Barbershop'', 34), (gen_random_uuid(), ''Spa & Massage'', 35), (gen_random_uuid(), ''Medical & Dental'', 36), (gen_random_uuid(), ''Therapy & Counseling'', 37), (gen_random_uuid(), ''Childcare & Nanny'', 38), (gen_random_uuid(), ''Elderly Care'', 39), (gen_random_uuid(), ''Event Planning'', 40), (gen_random_uuid(), ''DJ & Entertainment'', 41), (gen_random_uuid(), ''Videography'', 42), (gen_random_uuid(), ''Software Development'', 43), (gen_random_uuid(), ''Digital Marketing'', 44), (gen_random_uuid(), ''SEO & Content'', 45), (gen_random_uuid(), ''Administrative & Virtual Assistant'', 46), (gen_random_uuid(), ''Other'', 99) ON CONFLICT (name) DO NOTHING', v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.service_offerings (service_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, service_category_id UUID REFERENCES %I.service_categories(category_id) ON DELETE SET NULL, category VARCHAR(100), description TEXT, price DECIMAL(15, 2) NOT NULL, business_id UUID NOT NULL, delivery_type VARCHAR(20) NOT NULL DEFAULT ''PHYSICAL'' CHECK (delivery_type IN (''VIRTUAL'', ''PHYSICAL'')), duration_minutes INTEGER, is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.service_appointments (appointment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_id UUID NOT NULL REFERENCES %I.service_offerings(service_id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE RESTRICT, requested_date DATE NOT NULL, requested_time TIME, status VARCHAR(20) NOT NULL DEFAULT ''PENDING'' CHECK (status IN (''PENDING'', ''CONFIRMED'', ''COMPLETED'', ''CANCELLED'', ''NO_SHOW'')), notes TEXT, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema, v_schema);
    EXECUTE format('CREATE TABLE IF NOT EXISTS %I.service_booking_payments (payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), appointment_id UUID NOT NULL REFERENCES %I.service_appointments(appointment_id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES %I.users(user_id) ON DELETE RESTRICT, amount DECIMAL(15, 2) NOT NULL, transaction_id TEXT, payment_status VARCHAR(20) NOT NULL DEFAULT ''pending'' CHECK (payment_status IN (''pending'', ''completed'', ''failed'', ''cancelled'')), payment_method VARCHAR(50) DEFAULT ''M-Pesa'', created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)', v_schema, v_schema, v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_users_email ON %I.users(email)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_verification_codes_user ON %I.verification_codes(user_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_verification_codes_expires ON %I.verification_codes(expires_at)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON %I.password_reset_tokens(token)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token_hash ON %I.password_reset_tokens(token_hash)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires ON %I.password_reset_tokens(expires_at)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_product_categories_display_order ON %I.product_categories(display_order)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_products_business_id ON %I.products(business_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_inventory_images_product ON %I.inventory_images(product_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_orders_user ON %I.orders(user_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_orders_status ON %I.orders(order_status)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_orders_ordered_at ON %I.orders(ordered_at)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_order_items_order ON %I.order_items(order_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_payments_order ON %I.payments(order_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_shipments_order ON %I.shipments(order_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_shipments_assigned_courier ON %I.shipments(assigned_courier_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_expenses_date ON %I.expenses(expense_date)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_expenses_category ON %I.expenses(category)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_categories_display_order ON %I.service_categories(display_order)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_offerings_business_id ON %I.service_offerings(business_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_offerings_service_category_id ON %I.service_offerings(service_category_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_offerings_delivery_type ON %I.service_offerings(delivery_type)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_offerings_category ON %I.service_offerings(category)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_appointments_service ON %I.service_appointments(service_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_appointments_user ON %I.service_appointments(user_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_appointments_date ON %I.service_appointments(requested_date)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_booking_payments_appointment ON %I.service_booking_payments(appointment_id)', v_schema);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_service_booking_payments_transaction ON %I.service_booking_payments(transaction_id)', v_schema);
    UPDATE public.tenants SET schema_name = v_schema, updated_at = CURRENT_TIMESTAMP WHERE tenant_id = p_tenant_id;
END;
$$ LANGUAGE plpgsql;
